FROM jo7oem/go-tutor:latest
LABEL maintainer="jo7oem@ume-ch.net"

ENV LANG ja_JP.UTF-8

ENV GOPATH /go/src
ENV GO111MODULE=on

RUN go install golang.org/x/tools/gopls@latest &&\
    go install github.com/go-delve/delve/cmd/dlv@latest
RUN curl -fsSL https://code-server.dev/install.sh | sh
RUN code-server \
  --install-extension ms-ceintl.vscode-language-pack-ja \
  --install-extension golang.Go
ADD ./VSCode_config.yaml /root/.config/code-server/config.yaml

ENV GO111MODULE=off
EXPOSE 8080
ENTRYPOINT ["code-server"]
