FROM golang:1.22 AS builder
LABEL maintainer="jo7oem@ume-ch.net"

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG ja_JP.UTF-8

ENV GOPATH /go/src
ENV GO111MODULE=on

RUN apt-get update && \
    apt-get install -y locales && \
    ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    sed -i -E "s/# (${LANG})/\1/" /etc/locale.gen && \
    locale-gen && \
    apt-get install -y curl wget tzdata file locales bash-completion && \
    apt-get install -y vim-nox vim-snippets emacs-nox nano && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
RUN go install golang.org/x/tools/gopls@latest &&\
    go install github.com/go-delve/delve/cmd/dlv@latest
RUN curl -fsSL https://code-server.dev/install.sh | sh
RUN code-server \
  --install-extension ms-ceintl.vscode-language-pack-ja \
  --install-extension golang.Go
ADD ./VSCode_config.yaml /root/.config/code-server/config.yaml
ADD ./VSCode_settings.json /root/.local/share/code-server/User/settings.json
ADD ./.vscode /root/go-tutor/.vscode
ADD ./samples /root/go-tutor/samples
ADD ./go_tutorial /root/go-tutor/go_tutorial

ENV GO111MODULE=off
EXPOSE 8888
ENTRYPOINT ["code-server"]
